Repository pokt-network/smt, pull requests merged in 2023-12, with the labels that each got.

#29 chore: tidy up documentation and github workflows/templates
  .github/ISSUE_TEMPLATE/issue.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/pull_request_template.md
  .github/workflows/test.yml
  .gitignore
  README.md
  docs/KVStore.md
  docs/MerkleSumTree.md
  docs/SMT.md
  godoc.go
  proofs.go
Labels: large, waiting-for-review

#30 Update proofs.go
  proofs.go
Labels: small, waiting-for-review

#32 [Documentation] Add clarifying comment to `ClosestProof` documentation
  docs/SMT.md
Labels: documentation, small, waiting-for-review
