Repository pokt-network/smt, pull requests merged in 2024-01, with the labels that each got.

#35 fix whitepaper link
  README.md
Labels: documentation, small, waiting-for-review

#36 [Bug] Fix bug introduced by changing `BigEndian` to `LittleEndian`
  benchmarks/proof_sizes_test.go
  docs/MerkleSumTrie.md
  fuzz_test.go
  hasher.go
  proofs.go
  proofs_test.go
  smst.go
  smst_proofs_test.go
  smst_test.go
  smst_utils_test.go
  smt_proofs_test.go
  utils.go
Labels: bug, small, waiting-for-review

#34 [Documentation] Cleanup Docs and Workflows
  .github/codecov.yml
  .github/workflows/test.yml
  .gitignore
  README.md
  docs/benchmarks.md
  docs/kvstore.md
  docs/merkle-sum-trie.md
  docs/smt.md
Labels: enhancement, large, waiting-for-review, code health

#33 [Enhancement] Reintroduce the `MapStore` interface and `SimpleMap` and make the `Badger` a submodules
  .github/workflows/test.yml
  Makefile
  README.md
  benchmarks/bench_leaf_test.go
  benchmarks/bench_smst_test.go
  benchmarks/bench_smt_test.go
  benchmarks/bench_utils_test.go
  benchmarks/proof_sizes_test.go
  bulk_test.go
  docs/badger-store.md
  docs/mapstore.md
  docs/merkle-sum-trie.md
  docs/smt.md
  errors.go
  fuzz_test.go
  go.mod
  go.sum
  go.work
  go.work.sum
  godoc.go
  kvstore/badger/errors.go
  kvstore/badger/go.mod
  kvstore/badger/go.sum
  kvstore/badger/godoc.go
  kvstore/badger/interface.go
  kvstore/badger/kvstore.go
  kvstore/badger/kvstore_test.go
  kvstore/godoc.go
  kvstore/interfaces.go
  kvstore/simplemap/errors.go
  kvstore/simplemap/godoc.go
  kvstore/simplemap/simplemap.go
  kvstore/simplemap/simplemap_test.go
  proofs.go
  proofs_test.go
  smst.go
  smst_example_test.go
  smst_proofs_test.go
  smst_test.go
  smst_utils_test.go
  smt.go
  smt_example_test.go
  smt_proofs_test.go
  smt_test.go
  smt_utils_test.go
  types.go
Labels: enhancement, large, waiting-for-review, code health

#37 [Enhancement] Add MerkleRoot type alias for []byte with Sum method
  docs/merkle-sum-trie.md
  docs/smt.md
  root_test.go
  smst.go
  smt.go
  types.go
Labels: enhancement, medium, waiting-for-review
